# Generated by Django 5.2.16 on 2026-08-03 09:57

import django.core.validators
import django.db.models.deletion
import teacher.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_subject_alter_teacher_salary_type_contract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), teacher.models.validate_contract_file_size]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
