# Generated by Django 5.2.16 on 2026-08-06 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_regax', models.CharField(max_length=255)),
                ('pasport_number', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('groups', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=50)),
                ('balans', models.BigIntegerField(default=0)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.UUIDField()),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
