<<<<<<< HEAD
# Generated by Django 5.2.16 on 2026-08-07 18:33
=======
# Generated by Django 5.2.16 on 2026-08-07 18:44
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text="To'lov oyi (masalan, 2026-08-01)")),
                ('course_price', models.DecimalField(decimal_places=2, help_text="12 darslik to'liq kurs narxi", max_digits=12)),
                ('total_lessons', models.PositiveIntegerField(default=12, help_text='Bir oydagi rejalashtirilgan standart darslar soni')),
                ('attended_lessons', models.PositiveIntegerField(default=0, help_text='Talaba amalda qatnashgan darslar soni')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, help_text="Davomatga ko'ra hisoblangan summa", max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text="Talaba amalda to'lagan summa", max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'liq to'langan")], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
=======
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_for', models.DateField(help_text="Qaysi oy uchun to'lov qilingani (masalan: 2026-08-01)")),
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1
            ],
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('month', models.DateField(help_text='Maosh oyi (masalan, 2026-08-01)')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text="12 dars o'tilganda beriladigan to'liq oylik", max_digits=12)),
                ('total_lessons', models.PositiveIntegerField(default=12, help_text='Bir oydagi rejalashtirilgan darslar soni')),
                ('conducted_lessons', models.PositiveIntegerField(default=0, help_text="O'qituvchi amalda o'tgan darslar soni")),
                ('calculated_salary', models.DecimalField(decimal_places=2, default=0, help_text="O'tilgan darslarga ko'ra hisoblangan maosh", max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan")], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
=======
                ('for_month', models.DateField(help_text='Qaysi oy uchun oylik berilayotgani (masalan: 2026-08-01)')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta / P2P'), ('bank', "Bank o'tkazmasi"), ('click_payme', 'Click / Payme')], default='cash', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1
            ],
        ),
    ]
