# Generated by Django 5.2.16 on 2026-08-07 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='groups.group'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='groups.group'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='teacher.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='studentpayment',
            unique_together={('student', 'group', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='teachersalary',
            unique_together={('teacher', 'group', 'month')},
        ),
    ]
