<<<<<<< HEAD
# Generated by Django 5.2.16 on 2026-08-07 18:33
=======
# Generated by Django 5.2.16 on 2026-08-07 18:44
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
<<<<<<< HEAD
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        ('teacher', '0001_initial'),
=======
        ('students', '0001_initial'),
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='studentpayment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='groups.group'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='groups.group'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='teacher.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='studentpayment',
            unique_together={('student', 'group', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='teachersalary',
            unique_together={('teacher', 'group', 'month')},
        ),
=======
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1
    ]
