# Generated by Django 5.2.16 on 2026-08-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_teacher_lessons_group'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='groups.lessons'),
        ),
    ]
