# Generated by Django 5.2.16 on 2026-08-07 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('days', models.CharField(choices=[('ODD', 'Toq kunlar'), ('EVEN', 'Juft kunlar'), ('ALL', 'Har kuni')], max_length=10)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('COMPLETED', 'Tugallangan'), ('RECENTLY', 'Kutilmoqda..')], default='ACTIVE', max_length=15)),
                ('room', models.CharField(max_length=100)),
                ('max_student', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_conducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
