<<<<<<< HEAD
# Generated by Django 5.2.16 on 2026-08-07 18:33
=======
# Generated by Django 5.2.16 on 2026-08-07 18:44
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
<<<<<<< HEAD
        ('teacher', '0001_initial'),
=======
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_groups', to='students.student'),
<<<<<<< HEAD
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='groups.group'),
=======
>>>>>>> fe439967a4c9f5b0fe6a6889a838d7af247ac1c1
        ),
    ]
